// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Zn42Jayp5ER5ytZDLW0tlZFWx70yoJY',
    appId: '1:840933901942:web:a4d2ca96e2f888930e0157',
    messagingSenderId: '840933901942',
    projectId: 'moodflix-app',
    authDomain: 'moodflix-app-11c77.firebaseapp.com',
    storageBucket: 'moodflix-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARN7YswcRVcli54by75SdoIEPFUENl7W4',
    appId: '1:840933901942:android:11b036586f02dbe20e0157',
    messagingSenderId: '840933901942',
    projectId: 'moodflix-app',
    storageBucket: 'moodflix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACoZYZjdNNJ35ybuTf_3WN08P2WbGm1-s',
    appId: '1:840933901942:ios:74afeda4db6cfdec0e0157',
    messagingSenderId: '840933901942',
    projectId: 'moodflix-app',
    storageBucket: 'moodflix-app.firebasestorage.app',
    iosBundleId: 'com.mucahitciftci.moodflix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACoZYZjdNNJ35ybuTf_3WN08P2WbGm1-s',
    appId: '1:840933901942:ios:74afeda4db6cfdec0e0157',
    messagingSenderId: '840933901942',
    projectId: 'moodflix-app',
    storageBucket: 'moodflix-app.firebasestorage.app',
    iosBundleId: 'com.mucahitciftci.moodflix',
  );
}
